[package]
name = "viu"
version = "1.1.0"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/atanunq/viu"
description = "View images right from the terminal."
categories = ["command-line-utilities"]
keywords = ["terminal", "image", "gif"]
exclude = ["img/*"]

[dependencies]
clap = "2.33"
crossterm = "0.17"
viuer = { path = "../viuer" }

[target.'cfg(target_os = "wasi")'.dependencies]
image = { version = "0.22.3", default-features = false, features = ["gif_codec", "jpeg", "ico", "jpeg-decoder", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"] }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
ctrlc = { version = "3.1", features = ["termination"] }
image = "0.23"
