[package]
name = "viu"
version = "0.2.1"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/atanunq/viu"
description = "View images right from the terminal."
exclude = ["img/*"]

[dependencies]
libc = "0.2"
clap = "2.33.0"
termcolor = "1.0.5"
gif = "0.10.2"
crossterm_terminal = "0.2.6"

[target.'cfg(target_os = "wasi")'.dependencies]
image = { version = "0.22.2", default-features = false, features = ["gif_codec", "jpeg", "ico", "jpeg-decoder", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"] }

[target.'cfg(not(target_os = "wasi"))'.dependencies]
ctrlc = { version = "3.1.3", features = ["termination"] }
image = "0.22.2"
