[package]
name = "viu"
version = "0.1.1"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/atanunq/viu"
description = "View images right from the terminal."
exclude = ["img/*"]

[dependencies]
libc = "0.2"
image = "0.21.1"
clap = "2.32.0"
termcolor = "1"
