[package]
name = "viu"
version = "0.2.2"
description = "A small command-line application to view images from the terminal"
readme = "README.md"
repository = "https://github.com/wapm-packages/viu"

[[module]]
name = "viu"
source = "target/wasm32-wasi/release/viu.wasm"
abi = "wasi"

[[command]]
name = "viu"
module = "viu"
